### ISSUE TITLE
Release v. Next

### ISSUE THREAD

**Issue by dblock** [dblock/ios-snapshot-test-case-expecta#51]
Follow https://github.com/dblock/ios-snapshot-test-case-expecta/blob/master/RELEASING.md. It needs some updates likely as it mentions Travis CI, too.

Want to do this @brainbicycle?

**Comment by brainbicycle** [comment]
hey happy to! I think I need to be added as an owner on the pod to push to trunk? registered under `brian<dot>beckerle<at>gmail<dot>com` 

also was thinking would be a minor version change since the API hasn't change but is a major change to deps, so was gonna go with `3.2.0`  but let me know if you want a different number.

**Comment by dblock** [comment]
Done. And yes, version makes sense.

**Comment by brainbicycle** [comment]
Thank you! One more hump to get over it seems, the pod is failing linting on Xcode 15.3 due to deps having old deployment targets and this issue: https://github.com/CocoaPods/CocoaPods/issues/12033 

Opened issues in the upstream repos but will look for a workaround in the meantime.

**Comment by brainbicycle** [comment]
Alright I worked around by point to a cocoapods fork with a higher minimum deployment version, 3.2.0 is live, thanks!

**Comment by dblock** [comment]
Thanks for your help @brainbicycle!
